# Form implementation generated from reading ui file 'src/editor/ui_editor_page.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from importlib.resources import path
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditorPage(object):
    def setupUi(self, EditorPage):
        EditorPage.setObjectName("EditorPage")
        self.centralWidget = QtWidgets.QWidget(parent=EditorPage)
        self.centralWidget.setObjectName("centralWidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 270, 90, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(EditorPage)
        QtCore.QMetaObject.connectSlotsByName(EditorPage)

    def retranslateUi(self, EditorPage):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton.setText(_translate("EditorPage", "Editor!!!"))

