# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x03\x61pi\"|\n\x04\x46low\x12\x12\n\nlocal_addr\x18\x01 \x01(\t\x12\x13\n\x0bremote_addr\x18\x02 \x01(\t\x12\x13\n\x0bl4_protocol\x18\x03 \x01(\t\x12\x13\n\x0bl7_protocol\x18\x04 \x01(\t\x12\x0f\n\x07request\x18\x05 \x01(\x0c\x12\x10\n\x08response\x18\x06 \x01(\x0c\"!\n\x05\x46lows\x12\x18\n\x05\x66lows\x18\x01 \x03(\x0b\x32\t.api.Flow\"\x17\n\x05Reply\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x0e\n\x0c\x41gentStarted\"\x06\n\x04NooP\"8\n\x07\x43ommand\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x1f\n\x08settings\x18\x02 \x01(\x0b\x32\r.api.Settings\"!\n\x08Settings\x12\x15\n\rcontainer_ids\x18\x01 \x03(\t\"\x16\n\x07Request\x12\x0b\n\x03num\x18\x01 \x01(\x05\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x9f\x01\n\x0bTrayceAgent\x12+\n\x11SendFlowsObserved\x12\n.api.Flows\x1a\n.api.Reply\x12\x31\n\x10SendAgentStarted\x12\x11.api.AgentStarted\x1a\n.api.Reply\x12\x30\n\x11OpenCommandStream\x12\t.api.NooP\x1a\x0c.api.Command(\x01\x30\x01\x42\'Z%github.com/evanrolfe/trayce_agent/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%github.com/evanrolfe/trayce_agent/api'
  _globals['_FLOW']._serialized_start=18
  _globals['_FLOW']._serialized_end=142
  _globals['_FLOWS']._serialized_start=144
  _globals['_FLOWS']._serialized_end=177
  _globals['_REPLY']._serialized_start=179
  _globals['_REPLY']._serialized_end=202
  _globals['_AGENTSTARTED']._serialized_start=204
  _globals['_AGENTSTARTED']._serialized_end=218
  _globals['_NOOP']._serialized_start=220
  _globals['_NOOP']._serialized_end=226
  _globals['_COMMAND']._serialized_start=228
  _globals['_COMMAND']._serialized_end=284
  _globals['_SETTINGS']._serialized_start=286
  _globals['_SETTINGS']._serialized_end=319
  _globals['_REQUEST']._serialized_start=321
  _globals['_REQUEST']._serialized_end=343
  _globals['_RESPONSE']._serialized_start=345
  _globals['_RESPONSE']._serialized_end=371
  _globals['_TRAYCEAGENT']._serialized_start=374
  _globals['_TRAYCEAGENT']._serialized_end=533
# @@protoc_insertion_point(module_scope)
