# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x03\x61pi\"\x8a\x01\n\x04\x46low\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x12\n\nlocal_addr\x18\x02 \x01(\t\x12\x13\n\x0bremote_addr\x18\x03 \x01(\t\x12\x13\n\x0bl4_protocol\x18\x04 \x01(\t\x12\x13\n\x0bl7_protocol\x18\x05 \x01(\t\x12\x0f\n\x07request\x18\x06 \x01(\x0c\x12\x10\n\x08response\x18\x07 \x01(\x0c\"!\n\x05\x46lows\x12\x18\n\x05\x66lows\x18\x01 \x03(\x0b\x32\t.api.Flow\"\x17\n\x05Reply\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x0e\n\x0c\x41gentStarted\"\x06\n\x04NooP\"8\n\x07\x43ommand\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x1f\n\x08settings\x18\x02 \x01(\x0b\x32\r.api.Settings\"!\n\x08Settings\x12\x15\n\rcontainer_ids\x18\x01 \x03(\t\"\x16\n\x07Request\x12\x0b\n\x03num\x18\x01 \x01(\x05\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\"P\n\tContainer\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\"0\n\nContainers\x12\"\n\ncontainers\x18\x01 \x03(\x0b\x32\x0e.api.Container2\xde\x01\n\x0bTrayceAgent\x12-\n\x11SendFlowsObserved\x12\n.api.Flows\x1a\n.api.Reply\"\x00\x12\x37\n\x16SendContainersObserved\x12\x0f.api.Containers\x1a\n.api.Reply\"\x00\x12\x33\n\x10SendAgentStarted\x12\x11.api.AgentStarted\x1a\n.api.Reply\"\x00\x12\x32\n\x11OpenCommandStream\x12\t.api.NooP\x1a\x0c.api.Command\"\x00(\x01\x30\x01\x42\'Z%github.com/evanrolfe/trayce_agent/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%github.com/evanrolfe/trayce_agent/api'
  _globals['_FLOW']._serialized_start=19
  _globals['_FLOW']._serialized_end=157
  _globals['_FLOWS']._serialized_start=159
  _globals['_FLOWS']._serialized_end=192
  _globals['_REPLY']._serialized_start=194
  _globals['_REPLY']._serialized_end=217
  _globals['_AGENTSTARTED']._serialized_start=219
  _globals['_AGENTSTARTED']._serialized_end=233
  _globals['_NOOP']._serialized_start=235
  _globals['_NOOP']._serialized_end=241
  _globals['_COMMAND']._serialized_start=243
  _globals['_COMMAND']._serialized_end=299
  _globals['_SETTINGS']._serialized_start=301
  _globals['_SETTINGS']._serialized_end=334
  _globals['_REQUEST']._serialized_start=336
  _globals['_REQUEST']._serialized_end=358
  _globals['_RESPONSE']._serialized_start=360
  _globals['_RESPONSE']._serialized_end=386
  _globals['_CONTAINER']._serialized_start=388
  _globals['_CONTAINER']._serialized_end=468
  _globals['_CONTAINERS']._serialized_start=470
  _globals['_CONTAINERS']._serialized_end=518
  _globals['_TRAYCEAGENT']._serialized_start=521
  _globals['_TRAYCEAGENT']._serialized_end=743
# @@protoc_insertion_point(module_scope)
