# Form implementation generated from reading ui file 'src/network/ui_flow_table_container.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from importlib.resources import path
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FlowTableContainer(object):
    def setupUi(self, FlowTableContainer):
        FlowTableContainer.setObjectName("FlowTableContainer")
        FlowTableContainer.resize(321, 232)
        self.verticalLayout = QtWidgets.QVBoxLayout(FlowTableContainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setContentsMargins(4, 6, 4, 6)
        self.searchLayout.setSpacing(4)
        self.searchLayout.setObjectName("searchLayout")
        self.searchBox = QtWidgets.QLineEdit(parent=FlowTableContainer)
        self.searchBox.setObjectName("searchBox")
        self.searchLayout.addWidget(self.searchBox)
        self.searchBtn = QtWidgets.QPushButton(parent=FlowTableContainer)
        self.searchBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.searchBtn.setObjectName("searchBtn")
        self.searchLayout.addWidget(self.searchBtn)
        self.containersBtn = QtWidgets.QPushButton(parent=FlowTableContainer)
        self.containersBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.containersBtn.setObjectName("containersBtn")
        self.searchLayout.addWidget(self.containersBtn)
        self.verticalLayout.addLayout(self.searchLayout)
        self.tableView = HoverableTableView(parent=FlowTableContainer)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)

        self.retranslateUi(FlowTableContainer)
        QtCore.QMetaObject.connectSlotsByName(FlowTableContainer)

    def retranslateUi(self, FlowTableContainer):
        _translate = QtCore.QCoreApplication.translate
        self.searchBox.setPlaceholderText(_translate("FlowTableContainer", "Search"))
        self.searchBtn.setText(_translate("FlowTableContainer", "Filters"))
        self.containersBtn.setText(_translate("FlowTableContainer", "Containers"))
from network.hoverable_table_view import HoverableTableView

