# Form implementation generated from reading ui file 'src/network/ui_network_page.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from importlib.resources import path
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NetworkPage(object):
    def setupUi(self, NetworkPage):
        NetworkPage.setObjectName("NetworkPage")
        NetworkPage.resize(880, 609)
        self.verticalLayout = QtWidgets.QVBoxLayout(NetworkPage)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_2 = QtWidgets.QSplitter(parent=NetworkPage)
        self.splitter_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.flowTableContainer = FlowTableContainer(parent=self.splitter_2)
        self.flowTableContainer.setObjectName("flowTableContainer")
        self.splitter = QtWidgets.QSplitter(parent=self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.requestTabs = QtWidgets.QTabWidget(parent=self.splitter)
        self.requestTabs.setObjectName("requestTabs")
        self.requestText = Qsci.QsciScintilla()
        self.requestText.setObjectName("requestText")
        self.requestTabs.addTab(self.requestText, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.requestTabs.addTab(self.tab_2, "")
        self.responseTabs = QtWidgets.QTabWidget(parent=self.splitter)
        self.responseTabs.setObjectName("responseTabs")
        self.responseText = Qsci.QsciScintilla()
        self.responseText.setObjectName("responseText")
        self.responseTabs.addTab(self.responseText, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.responseTabs.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.splitter_2)

        self.retranslateUi(NetworkPage)
        QtCore.QMetaObject.connectSlotsByName(NetworkPage)

    def retranslateUi(self, NetworkPage):
        _translate = QtCore.QCoreApplication.translate
        NetworkPage.setWindowTitle(_translate("NetworkPage", "Form"))
        self.requestTabs.setTabText(self.requestTabs.indexOf(self.requestText), _translate("NetworkPage", "Request"))
        self.requestTabs.setTabText(self.requestTabs.indexOf(self.tab_2), _translate("NetworkPage", "Body"))
        self.responseTabs.setTabText(self.responseTabs.indexOf(self.responseText), _translate("NetworkPage", "Response"))
        self.responseTabs.setTabText(self.responseTabs.indexOf(self.tab_4), _translate("NetworkPage", "Body"))
from PyQt6 import Qsci
from network.flow_table_container import FlowTableContainer

